### ISSUE TITLE
WebAPIが利用できている状態になる

### ISSUE THREAD

**Issue by jnuank** [ginyolith/ddd-modeling-ec-mob-kt#13]
## 完了条件
- `curl localhost:8080` を叩いたら、`Hello world!` が返ってくること。

## 目的
- ドメインがインターフェースに依存しないことを、ほくそ笑むため。
- インターフェースの中でもWebAPIを作るのが簡単そうだった。

## どのようにしてWebAPIを実現するか？
- Ktorを利用する

## なぜKtorを導入しようとしたか（技術選定）
- WebAPIの実装の中でも、Ktorの学習コストが低そうだった（Springや素で書くのと比べて）。

**Comment by mohira** [comment]
TODO
=========
- [x] Ktorを追加
- [x] WebAPIつくり
    - [x] Kotlinのバージョンを上げる(v1.3にしないといけない)
    - [x] Hello worldを返す
