### ISSUE TITLE
なかじまっくで開発できるようにする

### ISSUE THREAD

**Issue by mohira** [ginyolith/ddd-modeling-ec-mob-kt#14]
## 完了条件
- IDEAでBuildできるようになる

## 現状
- 下記のエラーが発生している

## エラーメッセージ
```
Could not determine Java version using executable /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java.
```

**Comment by mohira** [comment]
なんかダウンロードしたらいけた。

次のエラーは依存関係の問題らしい。

**Comment by mohira** [comment]
Dagger(DIコンテナ)が悪さしてたっぽい。

**Comment by naokiur** [comment]
## 発生条件
* Javaバージョン
    * 10
* ローカルGradleバージョン
    * v4.4
### 理由
* Gradle4.4はJava10だと動かないらしい

### 対応策
`gradle/wrapper/gradle-wrapper.propeties` ファイルの中の1行を、「●変更後」の状態にしたら、gradle buildができるようになった

●変更前
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
```

●変更後
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.9-all.zip
```
